language: csharp
os: linux		
dist: trusty
mono: latest
sudo: required
dotnet: 1.0.0-preview2-1-003177
install:
- dotnet restore
before_script:
- sh -e /etc/init.d/xvfb start
solution: "./Promact.OAuth.Client/Promact.OAuth.Client.sln"
notifications:
  email:
    on_success: change
    on_failure: always
script:
- dotnet build ./Promact.OAuth.Client/src/Promact.OAuth.Client -c Release
- dotnet build ./Promact.OAuth.Client/src/Promact.OAuth.Client.Test -c Release
- dotnet test ./Promact.OAuth.Client/src/Promact.OAuth.Client.Test/project.json -c Release 
deploy:
  provider: script
  skip_cleanup: true
  script:
    - cd ./Promact.OAuth.Client/src/Promact.OAuth.Client && nuget pack Promact.OAuth.Client.nuspec -Version 1.0.0.$TRAVIS_BUILD_NUMBER -IncludeReferencedProjects -Prop Configuration=Release && nuget push *.nupkg $NUGET_API_KEY -verbosity detailed
  on:
    branch: master
